/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newTransaksi.java
 *
 * Created on 15 Des 09, 9:33:35
 */

package cibps;

import java.sql.Connection;
import java.util.Vector;

/**
 *
 * @author Mr Zorro
 */
public class newTransaksi extends javax.swing.JFrame {

    private Connection koneksi;
    private Vector dbNoTransaksi;
    private Vector dbBarang;

    /** Creates new form newTransaksi */
    public newTransaksi() {
        initComponents();
        initFirst();
    }

    private void initFirst() {
        dbBarang = new Vector();
        dbNoTransaksi = new Vector();
        koneksi = Database.openConnection(koneksi);
        if (koneksi != null) {
            dbBarang = Database.loadDBBarang(koneksi);
            loadIDBarang();
            Vector dbTransaksi = Database.loadDBTransaksi(koneksi);
            if (dbTransaksi.isEmpty() == false) {
                for (int i = 0; i < dbTransaksi.size(); i++)
                    dbNoTransaksi.add(((Transaksi)dbTransaksi.get(i)).getNoTransaksi());
            }
            else
                return;
        }
    }

    private void loadIDBarang() {
        if (dbBarang.isEmpty())
            return;
        for (int i = 0; i < dbBarang.size(); i++) {
            Barang barang = (Barang) dbBarang.get(i);
            if (barang.getJumlahStok() > 0)
                cbxIDBarang.addItem(barang.getIdBarang());
        }
    }

    private String generateID() {
        String genID = null;
        if (dbNoTransaksi.isEmpty()) {
            genID = "TG00001";
        }
        else {
            genID = (String) dbNoTransaksi.get(dbNoTransaksi.size()-1);
            int tID = Integer.parseInt(genID.substring(2));
            do {
                tID++;
                genID = String.format("TG%05d", tID);
            } while (dbNoTransaksi.contains(genID));
        }
        return genID;
    }

    private boolean simpan() {
        if (txtNoTransaksi.getText().compareTo("") == 0)
            return false;
        if (spnWaktuTransaksi.getValue() == null)
            return false;
        if (txtJumlahTransaksi.getText().compareTo("") == 0)
            return false;
        if (Integer.valueOf(txtJumlahTransaksi.getText()) < 1)
            return false;
        if (((String)cbxIDBarang.getSelectedItem()).compareTo("NONE") == 0)
            return false;
        if (txtJumlahBarang.getText().compareTo("") == 0)
            return false;
        if (Integer.valueOf(txtJumlahBarang.getText()) < 1)
            return false;
        
        Transaksi transaksi = new Transaksi();
        transaksi.setNoTransaksi(txtNoTransaksi.getText());
        transaksi.setWaktuTransaksi((java.util.Date) spnWaktuTransaksi.getValue());
        transaksi.setJumlahTransaksi(Integer.valueOf(txtJumlahTransaksi.getText()));
        transaksi.setIdBarang(((String)cbxIDBarang.getSelectedItem()));

        Barang barang = new Barang();
        for (int i = 0; i < dbBarang.size(); i++) {
            if (((String)cbxIDBarang.getSelectedItem()).compareTo(((Barang)dbBarang.get(i)).getIdBarang()) == 0) {
                if (((Barang)dbBarang.get(i)).getJumlahStok()-Integer.valueOf(txtJumlahBarang.getText()) >= 0) {
                    barang.setIdBarang(((Barang)dbBarang.get(i)).getIdBarang());
                    barang.setNamaBarang(((Barang)dbBarang.get(i)).getNamaBarang());
                    barang.setHarga(((Barang)dbBarang.get(i)).getHarga());
                    barang.setJumlahStok(((Barang)dbBarang.get(i)).getJumlahStok() - Integer.valueOf(txtJumlahBarang.getText()));
                    break;
                }
                else
                    return false;
            }
        }
        return Database.insertTransaksiBaru(koneksi, transaksi, barang);
    }
    
    public void close() {
        this.setVisible(false);
        this.dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblNoTransaksi = new javax.swing.JLabel();
        txtNoTransaksi = new javax.swing.JTextField();
        lblWaktuTransaksi = new javax.swing.JLabel();
        lblJumlahTransaksi = new javax.swing.JLabel();
        txtJumlahTransaksi = new javax.swing.JTextField();
        lblIDBarang = new javax.swing.JLabel();
        btnGenerateID = new javax.swing.JButton();
        spnWaktuTransaksi = new javax.swing.JSpinner();
        cbxIDBarang = new javax.swing.JComboBox();
        lblNamaBarang = new javax.swing.JLabel();
        txtJumlahBarang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CIBPS [Tambah Transaksi]");
        setResizable(false);

        lblNoTransaksi.setText("No Transaksi");

        txtNoTransaksi.setEditable(false);

        lblWaktuTransaksi.setText("Waktu Transaksi");

        lblJumlahTransaksi.setText("Jumlah Transaksi");

        txtJumlahTransaksi.setEditable(false);
        txtJumlahTransaksi.setText("0");

        lblIDBarang.setText("ID Barang");

        btnGenerateID.setText("Generate");
        btnGenerateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateIDActionPerformed(evt);
            }
        });

        spnWaktuTransaksi.setModel(new javax.swing.SpinnerDateModel());
        spnWaktuTransaksi.setEditor(new javax.swing.JSpinner.DateEditor(spnWaktuTransaksi, "yyyy-MM-dd"));

        cbxIDBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE" }));
        cbxIDBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxIDBarangItemStateChanged(evt);
            }
        });

        lblNamaBarang.setText("None");

        txtJumlahBarang.setText("0");
        txtJumlahBarang.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtJumlahBarangCaretUpdate(evt);
            }
        });

        jLabel1.setText("X");

        txtHarga.setEditable(false);
        txtHarga.setText("0");
        txtHarga.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtHargaCaretUpdate(evt);
            }
        });

        jLabel2.setText("=");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJumlahTransaksi)
                    .addComponent(lblWaktuTransaksi)
                    .addComponent(lblNoTransaksi)
                    .addComponent(lblIDBarang))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnWaktuTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNoTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(cbxIDBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGenerateID, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(txtJumlahTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoTransaksi)
                    .addComponent(txtNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWaktuTransaksi)
                    .addComponent(spnWaktuTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlahTransaksi)
                    .addComponent(txtJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtJumlahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDBarang)
                    .addComponent(cbxIDBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamaBarang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (simpan() == false)
            System.err.println("Error: can not insert new Transaksi data");
        else
            close();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnGenerateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateIDActionPerformed
        txtNoTransaksi.setText(generateID());
    }//GEN-LAST:event_btnGenerateIDActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        close();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void cbxIDBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxIDBarangItemStateChanged
        if (cbxIDBarang.getSelectedIndex() > 0) {
            lblNamaBarang.setText(((Barang)dbBarang.get(cbxIDBarang.getSelectedIndex()-1)).getNamaBarang());
            txtHarga.setText(String.valueOf(((Barang)dbBarang.get(cbxIDBarang.getSelectedIndex()-1)).getHarga()));
        }
        else {
            lblNamaBarang.setText("None");
            txtHarga.setText("0");
        }
    }//GEN-LAST:event_cbxIDBarangItemStateChanged

    private void txtHargaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtHargaCaretUpdate
        if (txtHarga.getText().compareTo("") == 0)
            return;
        if (txtJumlahBarang.getText().compareTo("") == 0)
            return;
        int harga = Integer.valueOf(txtHarga.getText());
        int jumlah = Integer.valueOf(txtJumlahBarang.getText());
        int total = harga * jumlah;
        txtJumlahTransaksi.setText(String.valueOf(total));
    }//GEN-LAST:event_txtHargaCaretUpdate

    private void txtJumlahBarangCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtJumlahBarangCaretUpdate
        if (txtHarga.getText().compareTo("") == 0)
            return;
        if (txtJumlahBarang.getText().compareTo("") == 0)
            return;
        int harga = Integer.valueOf(txtHarga.getText());
        int jumlah = Integer.valueOf(txtJumlahBarang.getText());
        int total = harga * jumlah;
        txtJumlahTransaksi.setText(String.valueOf(total));
    }//GEN-LAST:event_txtJumlahBarangCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnGenerateID;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cbxIDBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIDBarang;
    private javax.swing.JLabel lblJumlahTransaksi;
    private javax.swing.JLabel lblNamaBarang;
    private javax.swing.JLabel lblNoTransaksi;
    private javax.swing.JLabel lblWaktuTransaksi;
    private javax.swing.JSpinner spnWaktuTransaksi;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlahBarang;
    private javax.swing.JTextField txtJumlahTransaksi;
    private javax.swing.JTextField txtNoTransaksi;
    // End of variables declaration//GEN-END:variables

}
