/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TableBarang.java
 *
 * Created on 03 Des 09, 10:06:26
 */

package cibps;

import java.sql.Connection;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Mr Zorro
 */
public class TableBarang extends javax.swing.JPanel {

    public final int sizeWidth = 640;
    public final int sizeHeight = 480;
    
    private Connection koneksi;
    private Vector dbBarang;

    /** Creates new form TableBarang */
    public TableBarang() {
        initComponents();
        initFirst();
    }

    private void initFirst() {
        dbBarang = new Vector();
        koneksi = Database.openConnection(koneksi);
        if (koneksi != null) {
            dbBarang = Database.loadDBBarang(koneksi);
            showDatabase();
        }
    }

    private void showDatabase() throws IllegalArgumentException {
        if (dbBarang.isEmpty())
            return;
        try {
            DefaultTableModel dtm = (DefaultTableModel) masterTable.getModel();
            for (int i = 0; i < dbBarang.size(); i++) {
                int idx = -1;
                Barang record = (Barang) dbBarang.get(i);
                dtm.addRow(new Object[dtm.getColumnCount()]);
                TableColumnModel tcm = masterTable.getColumnModel();
                for (int j = 0; j < masterTable.getColumnCount(); j++) {
                    if (masterTable.getColumnName(j).compareTo("ID Barang") == 0)
                        if ((idx = tcm.getColumnIndex("ID Barang")) > -1)
                            dtm.setValueAt(record.getIdBarang(), i, idx);
                    if (masterTable.getColumnName(j).compareTo("Nama Barang") == 0)
                        if ((idx = tcm.getColumnIndex("Nama Barang")) > -1)
                            dtm.setValueAt(record.getNamaBarang(), i, idx);
                    if (masterTable.getColumnName(j).compareTo("Harga") == 0)
                        if ((idx = tcm.getColumnIndex("Harga")) > -1)
                            dtm.setValueAt(record.getHarga(), i, idx);
                    if (masterTable.getColumnName(j).compareTo("Jumlah Stok") == 0)
                        if ((idx = tcm.getColumnIndex("Jumlah Stok")) > -1)
                            dtm.setValueAt(record.getJumlahStok(), i, idx);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(TableBarang.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }

    private void showSelectedElement() {
        int selIdx = masterTable.getSelectedRow();
        try {
            if (selIdx > -1) {
                Barang record = (Barang) dbBarang.get(selIdx);
                txtIDBarang.setText(record.getIdBarang().toString());
                txtNamaBarang.setText(record.getNamaBarang().toString());
                txtHarga.setText("" + record.getHarga());
                txtJumlahStok.setText("" + record.getJumlahStok());
            }
            else {
                txtIDBarang.setText("");
                txtNamaBarang.setText("");
                txtHarga.setText("");
                txtJumlahStok.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(TableBarang.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }

    public void refresh() {
        DefaultTableModel dtm = (DefaultTableModel) masterTable.getModel();
        int sum = dtm.getRowCount();
        for (int i = 0; i < sum; i++) {
            dtm.removeRow(0);
        }
        initFirst();
    }
/*
    private void hapus() {
        int index = masterTable.getSelectedRow();
        if (index == -1)
            return;
        Database.removeBarang(koneksi, ((Barang)dbBarang.get(index)).getIdBarang());
        dbBarang.remove(index);
        refresh();
    }
*/
    private void simpan() {
        if (masterTable.getSelectedRow() != -1) {
            Barang barang = new Barang();
            barang.setIdBarang(txtIDBarang.getText());
            barang.setNamaBarang(txtNamaBarang.getText());
            barang.setHarga(Integer.valueOf(txtHarga.getText()));
            barang.setJumlahStok(Integer.valueOf(txtJumlahStok.getText()));
            Database.updateBarang(koneksi, barang);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblIDBarang = new javax.swing.JLabel();
        txtIDBarang = new javax.swing.JTextField();
        lblNamaBarang = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        lblHarga = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        lblJumlahStok = new javax.swing.JLabel();
        txtJumlahStok = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnUbah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        masterTable.setAutoCreateRowSorter(true);
        masterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang", "Harga", "Jumlah Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        masterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(masterTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblIDBarang.setText("ID Barang");

        txtIDBarang.setEditable(false);

        lblNamaBarang.setText("Nama Barang");

        txtNamaBarang.setEditable(false);

        lblHarga.setText("Harga");

        txtHarga.setEditable(false);

        lblJumlahStok.setText("Jumlah Stok");

        txtJumlahStok.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHarga)
                    .addComponent(lblNamaBarang)
                    .addComponent(lblJumlahStok)
                    .addComponent(lblIDBarang))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJumlahStok, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(txtIDBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDBarang)
                    .addComponent(txtIDBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamaBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlahStok)
                    .addComponent(txtJumlahStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.setEnabled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.setEnabled(false);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUbah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambah)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbah)
                    .addComponent(btnTambah)
                    .addComponent(btnRefresh)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void masterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterTableMouseClicked
        showSelectedElement();
}//GEN-LAST:event_masterTableMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        newBarang bb = new newBarang();
        bb.setVisible(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        if (dbBarang.isEmpty() == false) {
            dbBarang.clear();
        }
        refresh();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (masterTable.getSelectedRow() == -1)
            return;
        txtNamaBarang.setEditable(false);
        txtHarga.setEditable(false);
        txtJumlahStok.setEditable(false);
        btnSimpan.setEnabled(false);
        //btnHapus.setEnabled(true);
        btnBatal.setEnabled(false);
        btnRefresh.setEnabled(true);
        btnTambah.setEnabled(true);
        btnUbah.setEnabled(true);
        simpan();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if (masterTable.getSelectedRow() == -1)
            return;
        txtNamaBarang.setEditable(true);
        txtHarga.setEditable(true);
        txtJumlahStok.setEditable(true);
        btnSimpan.setEnabled(true);
        //btnHapus.setEnabled(false);
        btnBatal.setEnabled(true);
        btnRefresh.setEnabled(false);
        btnTambah.setEnabled(false);
        btnUbah.setEnabled(false);
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        txtNamaBarang.setEditable(false);
        txtHarga.setEditable(false);
        txtJumlahStok.setEditable(false);
        btnSimpan.setEnabled(false);
        //btnHapus.setEnabled(true);
        btnBatal.setEnabled(false);
        btnRefresh.setEnabled(true);
        btnTambah.setEnabled(true);
        btnUbah.setEnabled(true);
        showSelectedElement();
    }//GEN-LAST:event_btnBatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblIDBarang;
    private javax.swing.JLabel lblJumlahStok;
    private javax.swing.JLabel lblNamaBarang;
    private javax.swing.JTable masterTable;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIDBarang;
    private javax.swing.JTextField txtJumlahStok;
    private javax.swing.JTextField txtNamaBarang;
    // End of variables declaration//GEN-END:variables

}
