/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TableTransaksi.java
 *
 * Created on 03 Des 09, 10:30:53
 */

package cibps;

import java.sql.Connection;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Mr Zorro
 */
public class TableTransaksi extends javax.swing.JPanel {

    public final int sizeWidth = 640;
    public final int sizeHeight = 480;
    
    private Connection koneksi;
    private Vector dbTransaksi;

    /** Creates new form TableTransaksi */
    public TableTransaksi() {
        initComponents();
        initFirst();
    }

    private void initFirst() {
        dbTransaksi = new Vector();
        koneksi = Database.openConnection(koneksi);
        if (koneksi != null) {
            dbTransaksi = Database.loadDBTransaksi(koneksi);
            showDatabase();
        }
    }

    private void showDatabase() {
        if (dbTransaksi.isEmpty())
            return;
        try {
            DefaultTableModel dtm = (DefaultTableModel) masterTable.getModel();
            for (int i = 0; i < dbTransaksi.size(); i++) {
                int idx = -1;
                Transaksi record = (Transaksi) dbTransaksi.get(i);
                dtm.addRow(new Object[dtm.getColumnCount()]);
                TableColumnModel tcm = masterTable.getColumnModel();
                for (int j = 0; j < masterTable.getColumnCount(); j++) {
                    if (masterTable.getColumnName(j).compareTo("No Transaksi") == 0)
                        if ((idx = tcm.getColumnIndex("No Transaksi")) > -1)
                            dtm.setValueAt(record.getNoTransaksi(), i, idx);
                    if (masterTable.getColumnName(j).compareTo("Waktu Transaksi") == 0)
                        if ((idx = tcm.getColumnIndex("Waktu Transaksi")) > -1)
                            dtm.setValueAt(record.getWaktuTransaksi(), i, idx);
                    if (masterTable.getColumnName(j).compareTo("Jumlah Transaksi") == 0)
                        if ((idx = tcm.getColumnIndex("Jumlah Transaksi")) > -1)
                            dtm.setValueAt(record.getJumlahTransaksi(), i, idx);
                    if (masterTable.getColumnName(j).compareTo("ID Barang") == 0)
                        if ((idx = tcm.getColumnIndex("ID Barang")) > -1)
                            dtm.setValueAt(record.getIdBarang(), i, idx);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(TableTransaksi.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }

    private void showSelectedElement() {
        int selIdx = masterTable.getSelectedRow();
        try {
            if (selIdx > -1) {
                Transaksi record = (Transaksi) dbTransaksi.get(selIdx);
                txtNoTransaksi.setText(record.getNoTransaksi());
                txtWaktuTransaksi.setText(record.getWaktuTransaksi().toString());
                txtJumlahTransaksi.setText("" + record.getJumlahTransaksi());
                txtIDBarang.setText(record.getIdBarang());
            }
            else {
                txtNoTransaksi.setText("");
                txtWaktuTransaksi.setText("");
                txtJumlahTransaksi.setText("");
                txtIDBarang.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(TableTransaksi.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }

    public void refresh() {
        DefaultTableModel dtm = (DefaultTableModel) masterTable.getModel();
        int sum = dtm.getRowCount();
        for (int i = 0; i < sum; i++) {
            dtm.removeRow(0);
        }
        initFirst();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblNoTransaksi = new javax.swing.JLabel();
        txtNoTransaksi = new javax.swing.JTextField();
        lblWaktuTransaksi = new javax.swing.JLabel();
        txtWaktuTransaksi = new javax.swing.JTextField();
        lblJumlahTransaksi = new javax.swing.JLabel();
        txtJumlahTransaksi = new javax.swing.JTextField();
        lblIDBarang = new javax.swing.JLabel();
        txtIDBarang = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnStatistik = new javax.swing.JButton();

        masterTable.setAutoCreateRowSorter(true);
        masterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Transaksi", "Waktu Transaksi", "Jumlah Transaksi", "ID Barang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        masterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(masterTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblNoTransaksi.setText("No Transaksi");

        txtNoTransaksi.setEditable(false);

        lblWaktuTransaksi.setText("Waktu Transaksi");

        txtWaktuTransaksi.setEditable(false);

        lblJumlahTransaksi.setText("Jumlah Transaksi");

        txtJumlahTransaksi.setEditable(false);

        lblIDBarang.setText("ID Barang");

        txtIDBarang.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJumlahTransaksi)
                    .addComponent(lblWaktuTransaksi)
                    .addComponent(lblNoTransaksi)
                    .addComponent(lblIDBarang))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIDBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addComponent(txtWaktuTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addComponent(txtJumlahTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addComponent(txtNoTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoTransaksi)
                    .addComponent(txtNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWaktuTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWaktuTransaksi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlahTransaksi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDBarang)
                    .addComponent(txtIDBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnStatistik.setText("Statistik");
        btnStatistik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(381, Short.MAX_VALUE)
                .addComponent(btnStatistik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambah)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnRefresh)
                    .addComponent(btnStatistik))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void masterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterTableMouseClicked
        showSelectedElement();
}//GEN-LAST:event_masterTableMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        newTransaksi nt = new newTransaksi();
        nt.setVisible(true);
        refresh();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistikActionPerformed
        viewStatistik vs = new viewStatistik();
        vs.setVisible(true);
    }//GEN-LAST:event_btnStatistikActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnStatistik;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIDBarang;
    private javax.swing.JLabel lblJumlahTransaksi;
    private javax.swing.JLabel lblNoTransaksi;
    private javax.swing.JLabel lblWaktuTransaksi;
    private javax.swing.JTable masterTable;
    private javax.swing.JTextField txtIDBarang;
    private javax.swing.JTextField txtJumlahTransaksi;
    private javax.swing.JTextField txtNoTransaksi;
    private javax.swing.JTextField txtWaktuTransaksi;
    // End of variables declaration//GEN-END:variables

}
