/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TableKas.java
 *
 * Created on 03 Des 09, 11:07:39
 */

package cibps;

import java.sql.Connection;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Mr Zorro
 */
public class TableKas extends javax.swing.JPanel {

    public final int sizeWidth = 640;
    public final int sizeHeight = 480;
    private Connection koneksi;
    private Vector dbTransaksi;
    private Vector dbKas;

    /** Creates new form TableKas */
    public TableKas() {
        initComponents();
        initFirst();
    }

    private void initFirst() {
        dbTransaksi = new Vector();
        dbKas = new Vector();
        koneksi = Database.openConnection(koneksi);
        if (koneksi != null) {
            dbKas = Database.loadDBKas(koneksi);
            dbTransaksi = Database.loadDBTransaksi(koneksi);
            calculateKas();
            showDatabase();
        }
    }

    private void calculateKas() {
        Vector<java.util.Date> dates = new Vector();
        for (int i = 0; i < dbTransaksi.size(); i++) {
            if (dates.contains(((Transaksi)dbTransaksi.get(i)).getWaktuTransaksi()) == false) {
                dates.add(((Transaksi)dbTransaksi.get(i)).getWaktuTransaksi());
            }
        }
        for (int i = 0; i < dates.size(); i++) {
            Kas kas = new Kas();
            kas.setTanggal(dates.get(i));
            kas.setSaldo(0);
            dbKas.add(kas);
        }
        for (int i = 0; i < dbKas.size(); i++) {
            for (int j = 0; j < dbTransaksi.size(); j++) {
                Kas kas = (Kas) dbKas.get(i);
                Transaksi trans = (Transaksi) dbTransaksi.get(j);
                if (kas.getTanggal().compareTo(trans.getWaktuTransaksi()) == 0)
                    kas.setSaldo(trans.getJumlahTransaksi() + kas.getSaldo());
            }
        }
    }

    private void showDatabase() {
        if (dbKas.isEmpty())
            return;
        try {
            DefaultTableModel dtm = (DefaultTableModel) masterTable.getModel();
            for (int i = 0; i < dbKas.size(); i++) {
                int idx = -1;
                Kas record = (Kas) dbKas.get(i);
                dtm.addRow(new Object[dtm.getColumnCount()]);
                TableColumnModel tcm = masterTable.getColumnModel();
                for (int j = 0; j < masterTable.getColumnCount(); j++) {
                    if (masterTable.getColumnName(j).compareTo("Tanggal") == 0)
                        if ((idx = tcm.getColumnIndex("Tanggal")) > -1)
                            dtm.setValueAt(record.getTanggal(), i, idx);
                    if (masterTable.getColumnName(j).compareTo("Saldo") == 0)
                        if ((idx = tcm.getColumnIndex("Saldo")) > -1)
                            dtm.setValueAt(record.getSaldo(), i, idx);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(TableKas.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }

    private void showSelectedElement() {
        int selIdx = masterTable.getSelectedRow();
        try {
            if (selIdx > -1) {
                Kas record = (Kas) dbKas.get(selIdx);
                txtTanggal.setText(record.getTanggal().toString());
                txtSaldo.setText("" + record.getSaldo());
            }
            else {
                txtTanggal.setText("");
                txtSaldo.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(TableBarang.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }

    public void refresh() {
        DefaultTableModel dtm = (DefaultTableModel) masterTable.getModel();
        int sum = dtm.getRowCount();
        for (int i = 0; i < sum; i++) {
            dtm.removeRow(0);
        }
        initFirst();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        lblSaldo = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        masterTable.setAutoCreateRowSorter(true);
        masterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        masterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(masterTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblTanggal.setText("Tanggal");

        txtTanggal.setEditable(false);

        lblSaldo.setText("Saldo");

        txtSaldo.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblTanggal)
                        .addGap(32, 32, 32)
                        .addComponent(txtTanggal))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblSaldo)
                        .addGap(44, 44, 44)
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTanggal))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldo)))
        );

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan)
                .addContainerGap(490, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnSimpan))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void masterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterTableMouseClicked
        // TODO add your handling code here:
        //showSelectedElement();
        showSelectedElement();
}//GEN-LAST:event_masterTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        refresh();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JTable masterTable;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables

}
